/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchParamsImport } from './routes/searchParams'
import { Route as RoutesImport } from './routes/routes'
import { Route as RouterImport } from './routes/router'

// Create/Update Routes

const SearchParamsRoute = SearchParamsImport.update({
  id: '/searchParams',
  path: '/searchParams',
  getParentRoute: () => rootRoute,
} as any)

const RoutesRoute = RoutesImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRoute,
} as any)

const RouterRoute = RouterImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/router': {
      id: '/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof RouterImport
      parentRoute: typeof rootRoute
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesImport
      parentRoute: typeof rootRoute
    }
    '/searchParams': {
      id: '/searchParams'
      path: '/searchParams'
      fullPath: '/searchParams'
      preLoaderRoute: typeof SearchParamsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/router': typeof RouterRoute
  '/routes': typeof RoutesRoute
  '/searchParams': typeof SearchParamsRoute
}

export interface FileRoutesByTo {
  '/router': typeof RouterRoute
  '/routes': typeof RoutesRoute
  '/searchParams': typeof SearchParamsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/router': typeof RouterRoute
  '/routes': typeof RoutesRoute
  '/searchParams': typeof SearchParamsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/router' | '/routes' | '/searchParams'
  fileRoutesByTo: FileRoutesByTo
  to: '/router' | '/routes' | '/searchParams'
  id: '__root__' | '/router' | '/routes' | '/searchParams'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RouterRoute: typeof RouterRoute
  RoutesRoute: typeof RoutesRoute
  SearchParamsRoute: typeof SearchParamsRoute
}

const rootRouteChildren: RootRouteChildren = {
  RouterRoute: RouterRoute,
  RoutesRoute: RoutesRoute,
  SearchParamsRoute: SearchParamsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/router",
        "/routes",
        "/searchParams"
      ]
    },
    "/router": {
      "filePath": "router.tsx"
    },
    "/routes": {
      "filePath": "routes.tsx"
    },
    "/searchParams": {
      "filePath": "searchParams.ts"
    }
  }
}
ROUTE_MANIFEST_END */
